### ISSUE TITLE
Fix travis build for NWB bundle

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto.model.nwb#3]
The build is failing, see [here](https://travis-ci.org/openworm/org.geppetto.model.nwb). We need to understand how to use git-lfs from travis, I quickly attempted it but it doesn't work. See the travis configuration [here](https://github.com/openworm/org.geppetto.model.nwb/blob/development/.travis.yml)

**Comment by niteshthali08** [comment]
I have fixed this. Please check and let me know.

**Comment by tarelli** [comment]
@niteshthali08 great Nitesh, thanks!
